baseURL = "https://sumiya11.github.io/"
languageCode = "en-us"
title = "Alexander Demin"
theme = "sumiya"
publishDir = "public"
googleAnalytics = "G-40L5J69HWL"
# timeout=3000

[markup.goldmark.renderer]
unsafe= true

[params]
  # subtitle= "Bachelor student"
  # interests="Deep Reinforcement Learning, Machine Learning "
  # cv_name= "mycv.pdf"
  # blog="https://sumiya11.github.io/blog"

  custom_css = ["/css/main.css", "/css/normalize.css"]

[[params.affilation]]
  name = "HSE University"
  # position = "Bachelor student"
  contact = "asdemin_2@edu.hse.ru"

# [[params.affilation]]
#   name = "MyCoolStartup"
#   position = "Co-Founder"
#   contact = "hadi@mycoolstartup.ai"

[[params.social]]
  name = "Google Scholar"
  icon = "book"
  url = "https://scholar.google.com/citations?user=UDodLb4AAAAJ&hl=en"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/sumiya11"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/alexander-demin-399166221"

[[params.introduction.paragraph]]
  text="""Hi, I am Alex!"""
[[params.introduction.paragraph]]
  text="""I am an undergraduate student in Computer Science at HSE University."""
[[params.introduction.paragraph]]
  text="""Before, I was fortunate to work with Gleb Pogudin and Joris van der Hoeven at École Polytechnique, Tommaso Dorigo at INFN, Hamid Rahkooy and Thomas Sturm at Max Planck Institute for Informatics, and numerous other amazing collaborators."""
[[params.introduction.paragraph]]
  text="""Some of my publications can be found at [Google Scholar](https://scholar.google.com/citations?user=UDodLb4AAAAJ&hl=en)."""

[[params.publications]]

[[params.publications.paper]]
  name = "Exact linear reductions of dynamical models"
  authors = "__Alexander Demin__, Elizaveta Demitraki, and Gleb Pogudin"
  dest  = "preprint"
  # link = "https://mypaperishere.com"
  code_link = "https://github.com/x3042/ExactODEReduction.jl"
  arxiv_link = "https://arxiv.org/abs/2301.11653"

[[params.publications.paper]]
  name = "F5: A REDUCE Package for Signature-based Gröbner Basis Computation"
  authors = "__Alexander Demin__, Hamid Rahkooy, and Thomas Sturm"
  dest  = "Computer Algebra in Scientific Computing 2022"
  # link = "https://mypaperishere.com"
  # code_link = "https://thecoderepo.com"
  just_link = "https://hal.science/hal-03781962"
  # pdf_link = "F5_Reduce_CASC22.pdf"

[[params.publications.paper]]
  name = "A Semi-supervised Learning Method for the Search of Rare Processes in LHC Data"
  authors = "Hevjin Yarar, __Alexander Demin__, Tommaso Dorigo, Luca Quagliarella, and Andrey Ustyuzhanin"
  dest  = "Report 2.1 of INSIGHTS ITN to European Commission, 2022"
  # link = "mycv.pdf"
  # code_link = "mycv.pdf"
  pdf_link = "ranbox_report.pdf"

[[params.presentations]]

 [[params.presentations.presentation]]
  name = "__Invited talk__, Finding exact linear reductions of dynamical models"
  description  = "Ecole Polytechnique, The MAX Team seminar, France, 2023"
  # project_page = "https://myprojecthomepage.com"
  # code_link = "https://coderepo.com"
  # blog_link = "https://ablogpost.com"

  [[params.presentations.presentation]]
  name = "__Poster__, Automatic Optimization of Derivatives with Polyhedral Compiler"
  description  = "MODE Workshop on Differentiable Programming for Experiment Design, Greece, 2022"
  award = "Award-winning poster"
  # project_page = "https://myprojecthomepage.com"
  # code_link = "https://coderepo.com"
  # blog_link = "https://ablogpost.com"

  [[params.presentations.presentation]]
  name = "__Conference talk__, F5: A REDUCE Package for Signature-based Gröbner Basis Computation"
  description  = "Computer Algebra in Scientific Computing, Turkey, 2022 (online)"
  # project_page = "https://myprojecthomepage.com"
  # code_link = "https://coderepo.com"
  # blog_link = "https://ablogpost.com"

  [[params.presentations.presentation]]
  name = "__Invited talk__, Signature-based Algorithms for Computing Groebner Bases"
  description  = "Verification of Distributed Systems Group Seminar, France, 2022 (online)"
  # project_page = "https://myprojecthomepage.com"
  # code_link = "https://coderepo.com"
  # blog_link = "https://ablogpost.com"

    [[params.presentations.presentation]]
  name = "__Conference talk__, On some applications of Groebner bases"
  description  = "Scientific Student Conference, HSE University, Russia, 2022"
  award = "Best student talk"
  # project_page = "https://myprojecthomepage.com"
  # code_link = "https://coderepo.com"
  # blog_link = "https://ablogpost.com"

