baseURL = "https://sumiya11.github.io"
languageCode = "en-us"
title = "Alexander Demin"
theme = "avicenna2"
googleAnalytics = "UA-1234-6"
timeout=3000

[params]
  subtitle= "Bachelor student"
  # interests="Deep Reinforcement Learning, Machine Learning "
  cv_name= "mycv.pdf"
  blog="http://myblog.edu"

[[params.affilation]]
  name = "HSE University"
  position = "Bachelor student"
  contact = "asdemin_2[at]edu.hse.ru"

# [[params.affilation]]
#   name = "MyCoolStartup"
#   position = "Co-Founder"
#   contact = "hadi@mycoolstartup.ai"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/sumiya11"

# [[params.social]]
#   name = "Twitter"
#   icon = "twitter"
#   url = "https://twitter.com/hadisinaee"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/alexander-demin-399166221"

[[params.introduction.paragraph]]
  text="""Hi, I’m Alex!"""
[[params.introduction.paragraph]]
  text="""I am an undergraduate student in Computer Science at HSE University, majoring in machine learning. At the moment, I work at Max Planck Institute in the field of computer algebra."""
[[params.introduction.paragraph]]
  text="""Before, I was fortunate to work with Gleb Pogudin at Polytechnique de Paris, Tommaso Dorigo at INFN, and numerous other amazing collaborators."""

# [[params.projects]]
# 	[[params.projects.project]]
# 		name = "Velit egestas dui id ornare arcu odio ut sem. Nec nam aliquam sem et tortor"
# 		description  = "Enim facilisis gravida neque convallis a. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse.Velit egestas dui id ornare arcu odio ut sem. Nec nam aliquam sem et tortor. In nisl nisi scelerisque eu ultrices vitae auctor."
# 		project_page = "https://myprojecthomepage.com"
# 		code_link = "https://coderepo.com"
# 		blog_link = "https://ablogpost.com"
#
#  [[params.projects.project]]
# 		name = "In nisl nisi scelerisque eu ultrices vitae auctor"
# 		description  = ""
# 		project_page = "https://myprojecthomepage.com"
# 		code_link = "https://coderepo.com"
# 		blog_link = ""
#
#  [[params.projects.project]]
# 		name = "Integer eget aliquet nibh praesent tristique magna"
# 		description  = ""
# 		project_page = "https://myprojecthomepage.com"
# 		code_link = ""
# 		blog_link = "https://ablogpost.com"

[[params.publications]]
#  year="Preprint"

  [[params.publications.paper]]
    name = "F5: A REDUCE Package for Signature-based Gröbner Basis Computation"
    authors = "__Alexander Demin__, Hamid Rahkooy, and Thomas Sturm"
    dest  = "CASC 2022"
    # link = "https://mypaperishere.com"
    # code_link = "https://thecoderepo.com"
    # blog_link = "https://myblogaboutit.com"

  [[params.publications.paper]]
    name = "A Semi-supervised Learning Method for the Search of Rare Processes in LHC Data, 2022"
    authors = "Hevjin Yarar, __Alexander Demin__, Tommaso Dorigo, Luca Quagliarella, and Andrey Ustyuzhanin"
    dest  = "Report 2.1 of INSIGHTS ITN to European Commission"
    # link = "https://mypaperishere.com"
    # code_link = "https://thecoderepo.com"
    # blog_link = "https://myblogaboutit.com"

# [[params.publications]]
#   year="2019"
#
#   [[params.publications.paper]]
# 		name = "Feugiat sed lectus vestibulum mattis ullamcorper velit sed"
# 		authors = "Caroll Comes, __Hadi Sinaee__"
# 		dest  = "Udo Madhu Journal"
# 		link = "https://mypaperishere.com"
# 		code_link = "https://thecoderepo.com"
# 		blog_link = ""
#
#   [[params.publications.paper]]
# 		name = "Venenatis urna cursus eget nunc. Nam aliquam sem et tortor consequat id porta nibh venenatis"
# 		authors = "Les Larkins, Ana Alvardo, __Hadi Sinaee__ "
# 		dest  = "Zorka Vita Conference"
# 		link = "https://mypaperishere.com"
# 		code_link = ""
# 		blog_link = "https://myblogaboutit.com"
#
#   [[params.publications.paper]]
# 		name = "Aliquet eget sit amet tellus cras adipiscing enim eu turpis"
# 		authors = "Les Larkins, __Hadi Sinaee__, Ana Alvardo"
# 		dest  = "Lena Randa Conference"
# 		link = "https://mypaperishere.com"
# 		code_link = ""
# 		blog_link = ""
#
#   [[params.publications.paper]]
# 		name = "Orci eu lobortis elementum nibh tellus molestie nunc non blandit"
# 		authors = "__Hadi Sinaee__, Caroll Comes"
# 		dest  = "Thandeka Radhika Conference"
# 		link = ""
# 		code_link = ""
# 		blog_link = ""
